#!/usr/bin/env bash
# This script parses Apache log file, groups visitors by IP and HTTP status code,
# sorts by occurrence, and displays the data
awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn | awk '{print "    " $1 " " $2 " " $3}'
