#!/usr/bin/env bash
# Display all running processes, for all users, including those without a TTY, in a user-oriented format showing hierarchy
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
