#!/usr/bin/env bash
# This script creates a PID file, displays messages indefinitely, and handles signals

# Create the PID file
echo $$ > /var/run/myscript.pid

# Define signal handlers
trap 'echo "OK";rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
