#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process silently
# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)
# Kill the process silently
if [ -n "$pid" ]; then
    kill "$pid"
fi
