#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall
# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)
# Send the TERM signal to the process
if [ -n "$pid" ]; then
    pkill -TERM -f 4-to_infinity_and_beyond
fi
