#!/usr/bin/env bash
# This script kills the 7-highlander process

# Get the PID of the 7-highlander process
pid=$(pgrep -f 7-highlander)

# Send the TERM signal to the process
if [ -n "$pid" ]; then
    pkill -TERM -f 7-highlander
fi
