#!/usr/bin/env bash
# This script forcefully kills the 7-highlander process

# Get the PID of the 7-highlander process
pid=$(pgrep -f 7-highlander)

# Send the KILL signal to the process
if [ -n "$pid" ]; then
    pkill -KILL -f 7-highlander
    echo "OK"
fi
